[package]
name = "invalid_session"
version = "0.1.0"
authors = ["Scott <707090scott@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.67"

[dev-dependencies]
wasm-bindgen-test = "0.3.17"
